def show_help(error: bool = False) -> int:
    print("Usage: fcc [options] file[s]")
    print("\nOptions:")
    print("  > -h               Display this help message.")
    print("  > -help            Display this help message.")
    print("  > -?               Display this help message.")
    print("  > -o <output>      Specify the output file.")
    print("  > -e <entry>       Specify the entry point.")
    print("  > -c               Compile only.")
    print("  > -E<error>        Specify an error to be thrown.")
    print("  > -W<warning>      Specify a warning to be thrown.")
    print("  > -arch=<arch>     Specify the architecture to compile for.")
    print("\nExamples:")
    print("  fcc -Werror -arch=X86_64 -o progName file.fly file2.fly")
    return (84 if error else 0)