#!/usr/bin/python3

from genericpath import isdir, isfile
from os import mkdir
from shutil import copy2
from sys import argv, stderr, exit

"""
-- EPITECH PROJECT, 2024
-- Hub project
-- File description:
-- flo_to_exe
"""

from src import gen_c_code

def main() -> int:
    if (len(argv) != 2):
        stderr.write(f"{argv[0]}: invalid number of arguments.")
        return (1)

    if (not isfile(argv[1])):
        stderr.write(f"{argv[0]}: file {argv[1]} not found.")

    if (not isdir("generated")):
        mkdir("generated")

    wd ='/'.join(__file__.replace('\\', '/').split('/')[:-1])

    copy2(f"{wd}/assets/flo_to_exe.c", "./generated/")
    copy2(f"{wd}/assets/flo_to_exe.h", "./generated/")

    with open("./generated/binary.c", "w+") as fp:
        gen_c_code(argv[1], fp)

    return (0)

if (__name__ == "__main__"):
    exit(main())