#!/bin/bash

printf "\033[1m\033[38;2;255;0;0mMr_clean just passed here\n\033[0m"

# Conditions pour les fichiers à supprimer
conditions_list=(
    "-name '*~'"
    "-name '*#' -and -name '#*'"
    "-name '*.d'"
    "-name '*.o'"
    "-name '*.a'"
    "-name '*.cov'"
    "-name '*.gcda'"
    "-name '*.gcno'"
    "-name '*.gcov'"
    "-name '*.flo'"
)

# Banger absolu pour supprimer les fichiers
command="find . \( ${conditions_list[0]}"
for ((i=1; i<${#conditions_list[@]}; i++))
do
  command+=" -or ${conditions_list[$i]}"
done
command+=" \) -type f -delete"
eval "$command"
