#!/bin/python3

"""
-- EPITECH PROJECT, 2024
-- Hub project
-- File description:
-- fcc
"""

from sys import exit, argv
from genericpath import isfile
from src.floff import *
from src.fcc.compiler import Compiler

def read_code(file_path: str) -> str:
    data: str = None

    if (not isfile(file_path)):
        return (None)
    with open(file_path, 'r') as fp:
        data: str = fp.read()
    return (data)

def main() -> int:
    code: str = None

    if len(argv) < 2:
        print("Usage: fcc <filename>")
        return (84)
    for file in argv[1:]:
        code: str = read_code(file)

        if (not code):
            return (84)
        compiler: Compiler = Compiler(code, [], [], file)
        compiler.tokenize()
        compiler.compile()
    return (0)


if __name__ == "__main__":
    exit(main())
