.TH libstd 1 "06 Juillet 2024" "1.0" "LibStd man page"
.SH NAME
    String Functions - Functions for string operations

.SH SYNOPSIS
    fun ft_len(text)

.SH DESCRIPTION
    ft_len - Returns the length of the string pointed to by text.

.SH EXAMPLES
    var text = "Hello, world!"
    var len = ft_len(text)
    print(to_str(len))