.TH libstd 1 "06 Juillet 2024" "1.0" "LibStd man page"
.SH NAME
    Process Functions - Functions for process management

.SH SYNOPSIS
    fun quit(code)

.SH DESCRIPTION
    quit - Terminates the current process with the specified exit code.

.SH RETURN VALUE
    This function does not return a value.

.SH EXAMPLES
    fun main() [
        quit(0)
        => the part of the code after the quit function will not be executed
    ]
