.TH libstd 1 "06 Juillet 2024" "1.0" "LibStd man page"
.SH NAME
    File Functions - Functions for file operations

.SH SYNOPSIS
    fun read_file(filename)

.SH DESCRIPTION
    read_file - Reads the entire contents of the file specified by filename into a new buffer.

.SH RETURN VALUE
    Returns the content of the file as a string. If the file does not exist, an error is displayed and the program returns nil.

.SH EXAMPLES
    fun main() [
        var content = read_file("myfile.txt")
        print(content)
    ]
