.TH libstd 1 "06 Juillet 2024" "1.0" "LibStd man page"
.SH NAME
    Conversion Functions - Functions for data type conversions

.SH SYNOPSIS
    fun to_str(num)

.SH DESCRIPTION
    to_str - Converts an integer to a string.

.SH RETURN VALUE
    Returns a string representation of the integer.

.SH EXAMPLES
    var num = 123
    var str = to_str(num);
    print(str, 1, 1);
