.\" Manpage for Fluxify VM.
.TH flvm 1 "15 April 2024" "1.0" "flvm man page"
.SH NAME
flvm \- Fluxify VM
.SH DESCRIPTION
Fluxify VM is an interpreter for .flo object files
.br

.br
here is the opcode of the differents instructions
.br
    ┌─────────────────────────────────────────────┐
    │                Instructions                 │
    ├─────────────────────────────────────────────┤
    │  Code   Name   Args                         │
    ├─────────────────────────────────────────────┤
    │  00     NOOP   00                           │
    │  01     ADD    02                           │
    │  02     SUB    02                           │
    └─────────────────────────────────────────────┘

.br

.br
