.\" Manpage for Fluxify VM.
.TH flvm 1 "15 April 2024" "1.0" "flvm man page"
.SH NAME
flvm \- Fluxify VM
.SH DESCRIPTION
Fluxify VM is an interpreter for .flo object files
.br

.br
here is the opcode of the differents instructions
.br
    ┌─────────────────────────────────────────────┐
    │                Instructions                 │
    ├─────────────────────────────────────────────┤
    │  Code   Name   Args                         │
    ├─────────────────────────────────────────────┤
    │  00     NOOP   00                           │
    │  01     ADD    02                           │
    │  02     SUB    02                           │
    └─────────────────────────────────────────────┘

.br

.br
instructions are set in a table "Program" (0x02) containing all the instructions side by side
.br
  64 bits:
    ┌─────────────────────────────────────────────┐
    │                Program table                │
    ├─────────────────────────────────────────────┤
    │  Size   Name                                │
    ├─────────────────────────────────────────────┤
    │  08     Instruction                         │
    │  01     Argument size                       │
    │  08     Arg0                                │
    │  08     Arg1                                │
    │  08     ...                                 │
    └─────────────────────────────────────────────┘
.br

.br
  32 bits:
    ┌─────────────────────────────────────────────┐
    │                Program table                │
    ├─────────────────────────────────────────────┤
    │  Size   Name                                │
    ├─────────────────────────────────────────────┤
    │  04     Instruction                         │
    │  01     Argument size                       │
    │  04     Arg0                                │
    │  04     Arg1                                │
    │  04     ...                                 │
    └─────────────────────────────────────────────┘
.br

.br
instructions are referenced via another table "Label" (0x01) containing all reference to code segments
.br
  64 bits:
    ┌─────────────────────────────────────────────┐
    │                 Label table                 │
    ├─────────────────────────────────────────────┤
    │  Size   Name                                │
    ├─────────────────────────────────────────────┤
    │  01     Label name size                     │
    │  --     Label name                          │
    │  08     Refdest                             │
    └─────────────────────────────────────────────┘
.br

.br
  32 bits:
    ┌─────────────────────────────────────────────┐
    │                 Label table                 │
    ├─────────────────────────────────────────────┤
    │  Size   Name                                │
    ├─────────────────────────────────────────────┤
    │  01     Label name size                     │
    │  --     Label name                          │
    │  04     Refdest                             │
    └─────────────────────────────────────────────┘
.br

.br
contant datas are stored in a table "Constants" (0x03) that contain primitive C types such as:
numbers and strings
.br
  64 bits:
    ┌─────────────────────────────────────────────┐
    │               Constants table               │
    ├─────────────────────────────────────────────┤
    │  Size   Name                                │
    ├─────────────────────────────────────────────┤
    │  01     Value type                          │
    │  08     Value size                          │
    │  --     Value                               │
    └─────────────────────────────────────────────┘
.br

.br
  32 bits:
    ┌─────────────────────────────────────────────┐
    │               Constants table               │
    ├─────────────────────────────────────────────┤
    │  Size   Name                                │
    ├─────────────────────────────────────────────┤
    │  01     Value type                          │
    │  04     Value size                          │
    │  --     Value                               │
    └─────────────────────────────────────────────┘
.br

.br
Constant types :
    Int(): 0x01
    String(): 0x02
.br